[bot]
run = false

[bot.connect]
server_password = { pw = "", hashed = false, autohash = false }
channel_password = { pw = "", hashed = false, autohash = false }
client_version = { build = "", platform = "", sign = "" }
address = ""
channel = ""
name = "MusicBot"

[bot.connect.identity]
key = ""
offset = 0
level = -1

[bot.audio]
bitrate = 96
volume = { default = 50.0, min = 0.0, max = 100.0 }
max_user_volume = 100.0
send_mode = "voice"

[bot.commands]
matcher = "ic3"

[bot.reconnect]
ontimeout = ["1s", "2s", "5s", "10s", "30s", "1m", "5m", "repeat last"]
onerror = ["30s", "repeat last"]

[tools]
youtube-dl = { path = "/usr/local/bin/yt-dlp" }
ffmpeg = { path = "/usr/bin/ffmpeg" }

[web]
hosts = ["*"]
port = 58913

[web.api]
enabled = true
command_complexity = 64
matcher = "exact"

[web.api.ip]
address = "0.0.0.0"

[web.interface]
enabled = false

[rights]
path = "data/rights.toml"

[rights.default]
"+" = ["*"]

[configs]
bots_path = "data/bots"

[db]
path = "data/ts3audiobot.db"

[factories]
media = { path = "" }

[factories.youtube]
prefer_resolver = "YoutubeDl"

[plugins]
path = "data/plugins"
